application: pymed
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (dev/.*)|
 (tests/.*)|
 (license\.txt)|
 (setup.py)
 )$